name: custom_preload_videos
description: "A Flutter plugin designed to preload and cache videos for smooth playback within a PageView. It helps to eliminate buffering and provides a seamless video viewing experience by managing video assets proactively."
version: 0.0.9
homepage: https://github.com/aman246149/flutter-plugin/tree/master/preload_videos
repository: https://github.com/aman246149/flutter-plugin/tree/master/preload_videos

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.10.0
  chewie: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
