name: preload_videos
description: "A powerful and flexible Flutter video preloading package that allows you to create seamless video experiences by preloading a window of videos to ensure smooth playback as the user scrolls."
version: 1.0.0
homepage: https://github.com/your_username/preload_videos
repository: https://github.com/your_username/preload_videos

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.10.0
  chewie: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
